export const experienceList = [
  {
    id: 1,
    role: "Frontend Developer",
    company: "Company Name",
    duration: "Jan 2023 - Present",
    location: "Dhaka, Bangladesh",
    type: "Full-time",
    current: true,
    description: [
      "Developed and maintained responsive web applications using React.js and Next.js",
      "Collaborated with designers to translate Figma designs into pixel-perfect UI components",
      "Improved website performance and loading times through code optimization",
      "Integrated RESTful APIs and managed application state with Redux Toolkit",
    ],
    technologies: ["React", "Next.js", "Tailwind CSS", "Redux Toolkit"],
  },
  {
    id: 2,
    role: "Junior Frontend Developer",
    company: "Previous Company",
    duration: "Mar 2021 - Dec 2022",
    location: "Dhaka, Bangladesh",
    type: "Full-time",
    current: false,
    description: [
      "Built and maintained Drupal-based CMS websites for enterprise clients",
      "Created reusable UI components and maintained consistent design systems",
      "Worked with cross-functional teams to deliver projects on schedule",
      "Wrote clean, semantic HTML and CSS following accessibility best practices",
    ],
    technologies: ["Drupal", "SASS", "jQuery", "Bootstrap"],
  },
  {
    id: 3,
    role: "Web Developer Intern",
    company: "Internship Company",
    duration: "Jun 2020 - Feb 2021",
    location: "Dhaka, Bangladesh",
    type: "Internship",
    current: false,
    description: [
      "Assisted in building responsive websites using HTML, CSS, and JavaScript",
      "Learned modern web development practices and version control with Git",
      "Developed small features and fixed bugs under senior developer guidance",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap"],
  },
];
