import web1 from "../public/web1.png";
import psl from "../public/psl.png";
import edp from "../public/edp.png";
import scholarstone from "../public/scholarstone.png";
import smalls from "../public/smalls.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import gloz from "../public/gloz.png";
import web4 from "../public/web4.png";
import casp from "../public/casp.png";
import fmr from "../public/fmr.png";
import lls from "../public/lls.png";
import crabarian from "../public/crabarian.png";
import mkn from "../public/mkn.png";
import dt from "../public/dt.png";
import jazz from "../public/jazz.png";

export const portfolioList = [
  {
    name: "ScholarStone Academy",
    image: scholarstone,
    alt: "ScholarStone Academy",
    category: "webapp",
    id: 9,
    summary: "An online academy platform with course listings, student enrollment, and a modern learning experience.",
    description: [
      "Vue Js",
      "Tailwind CSS",
      "Swiper",
      "Headless UI",
      "Pinia",
      "Django Drf",
    ],
    live: "https://www.scholarstone.academy",
  },
  {
    name: "Exporter Crabarian",
    image: crabarian,
    alt: "Exporter Crabarian",
    category: "webapp",
    id: 11,
    summary: "A seafood export management platform enabling businesses to manage products, orders, and client communications.",
    description: [
      "Vue Js",
      "Tailwind CSS",
      "Ant Design",
      "Pinia",
      "Django Drf",
    ],
    live: "https://exporter.crabarian.com/",
  },
  {
    name: "Pollution Solution",
    image: psl,
    alt: "Pollution Solution",
    category: "drupal",
    id: 14,
    summary: "An environmental auditing and certification firm offering ESG reporting, sustainability verification, and compliance services to industry. Built on Drupal 11 with a clean, content-driven layout using Layout Builder.",
    description: ["Drupal 11", "SASS", "jQuery", "Layout Builder"],
    live: "https://www.pollution-solution.net/",
    github: "",
  },
  {
    name: "EduPolicy.ai",
    image: edp,
    alt: "EduPolicy.ai",
    category: "drupal",
    id: 15,
    summary: "A consultancy helping colleges and universities develop responsible AI policies and governance frameworks. Developed on Drupal 11 using Layout Builder for flexible, structured content management.",
    description: ["Drupal 11", "SASS", "jQuery", "Layout Builder"],
    live: "https://edupolicysite.idlewilddigital.com/",
    github: "",
  },
  {
    name: "CASP",
    image: casp,
    alt: "CASP",
    category: "drupal",
    id: 6,
    summary: "An interdisciplinary research initiative studying complex living phenomena like cognition and development. Upgraded from Drupal 9 to Drupal 11 and fully redesigned with a refreshed layout.",
    description: ["Drupal 11", "SASS", "jQuery", "Layout Builder"],
    live: "https://www.biologicalpurpose.org/",
    github: "",
  },
  {
    name: "Redux Commerce",
    image: web1,
    alt: "Redux Commerce",
    category: "webapp",
    id: 1,
    summary: "A fully functional e-commerce application with cart management, product filtering, and global state handled via Redux Toolkit.",
    description: [
      "React Js",
      "React Router",
      "React Bootstrap",
      "Redux Toolkit",
      "Tostify",
      "SASS",
    ],
    live: "https://rtk-commerce.netlify.app/",
    github: "https://github.com/sudipto68/redux-toolkit-ecommerce-pratice",
  },
  {
    name: "Midwest Kindey Network",
    image: mkn,
    alt: "MKN",
    category: "drupal",
    id: 9,
    summary: "A healthcare network website built to connect kidney patients and professionals with resources and support.",
    description: ["Backdrop CMS", "SASS", "jQuery", "Bootstrap"],
    live: "https://www.midwestkidneynetwork.org",
    github: "",
  },
  {
    name: "Dear Teacher",
    image: dt,
    alt: "Dear Teacher",
    category: "drupal",
    id: 12,
    summary: "An educational platform offering expert guidance and tools to help children succeed in school, from preschool through college. Upgraded from Drupal 9 to Drupal 11 and fully redesigned.",
    description: ["Drupal 11", "SASS", "jQuery", "Bootstrap"],
    live: "https://www.dearteacher.com",
    github: "",
  },
  {
    name: "Logic Layer Solutions",
    image: lls,
    alt: "Logic Layer Solutions",
    category: "react",
    id: 8,
    summary: "A corporate website for a software solutions company, featuring animated sections and a clean, professional design.",
    description: ["Next Js 16", "Tailwind Css", "Framer Motion"],
    live: "https://logiclayersolution.vercel.app",
    github: "",
  },
  {
    name: "Jazz Cultural",
    image: jazz,
    alt: "Jazz Cultural",
    category: "react",
    id: 13,
    summary: "A music room and café on Restaurant Row in Times Square, NYC — a tribute to Barry Harris and his Jazz Cultural Theater. Partner site of SmallsLive.",
    description: ["Vue JS", "Tailwind Css", "Framer Motion", "Axios"],
    live: "https://www.jazzcultural.com/",
    github: "",
  },
  {
    name: "Interrior",
    image: web2,
    alt: "Interrior",
    category: "react",
    id: 3,
    summary: "An interior design marketplace where users can browse services, connect with designers, and manage bookings.",
    description: [
      "React Js",
      "React Router",
      "React Bootstrap",
      "Express JS",
      "MongoDB",
      "Firebase",
    ],
    live: "https://interrior-366e5.web.app/",
    github: "https://github.com/sudipto68/Interrior-client",
  },
  {
    name: "Glozzom",
    image: gloz,
    alt: "Glozzom",
    category: "ui",
    id: 4,
    summary: "A responsive multi-section landing page with smooth animations and a modern visual design.",
    description: ["Html", "SASS", "Bootstrap"],
    live: "https://sudipto68.github.io/Glozzom/",
    github: "https://github.com/sudipto68/Glozzom",
  },
  {
    name: "Nike Clone",
    image: web4,
    alt: "Nike",
    category: "ui",
    id: 5,
    summary: "A pixel-perfect responsive clone of the Nike e-commerce storefront, built as a front-end practice project.",
    description: ["Html", "CSS", "Bootstrap"],
    live: "https://sudipto68.github.io/Responsive-Ecommerce-Web/",
    github: "https://github.com/sudipto68/Responsive-Ecommerce-Web",
  },
  {
    name: "FMR",
    image: fmr,
    alt: "FMR",
    category: "drupal",
    id: 7,
    summary: "A conservation nonprofit website built on Backdrop CMS, focused on accessibility and content-driven storytelling.",
    description: ["Backdrop CMS", "SASS", "jQuery"],
    live: "https://fmr.org/",
    github: "",
  },
  {
    name: "SmallsLive",
    image: smalls,
    alt: "SmallsLive",
    category: "django",
    id: 10,
    summary: "A live jazz streaming and archiving platform where fans can watch performances and explore a rich music library.",
    description: ["Python", "Django", "SASS", "Boostrap"],
    live: "https://smallslive.com/",
  },
];
