import Head from "next/head";
import {
  BsFillMoonFill,
  BsGithub,
  BsLinkedin,
  BsFacebook,
} from "react-icons/bs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sudipto Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10">
        <section>
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons uppercase tracking-widest">
              Sudipto
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonFill className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="text-white bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
        </section>
        <section className="text-center">
          <h2 className="text-3xl text-teal-500">Sudipto Kumar Mitra</h2>
          <h3 className="text-x py-2 text-gray-800 font-bold tracking-wider">
            Frontend Developer
          </h3>
          <p className=" text-md py-2 leading-6 text-gray-800">
            Experienced Frontend web Developer who likes problem solving and am
            a curious mind who loves learning. With hard work, dedication and
            persistence I always try to find effective solutions to complex
            problems. My objective is to continually grow via a rewarding and
            challenging career in software development.
          </p>
          <div className="flex gap-5 justify-center py-4">
            <BsGithub className="text-xl" />
            <BsLinkedin className="text-xl" />
            <BsFacebook className="text-xl" />
          </div>
        </section>
      </main>
    </>
  );
}
