import Head from "next/head";
import Nav from "./../components/Nav/nav.js";
import Intro from "../components/Intro/intro.js";
import Tech from "../components/Tech/tech.js";
import Service from "../components/Services/service.js";
import Portfolio from "../components/Portfolio/Portfolio.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sudipto Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10">
        <Nav />
        <Intro />
        <Tech />
        <Service />
        <Portfolio />
      </main>
    </>
  );
}
